model:
  checkpoint: ./pretrained_models/pretrained_aligndiff.pt #after training

sample:
  seed: 2021
  num_samples: 100
  num_steps: 1000
  pos_only: False
  center_pos_mode: protein
  sample_num_atoms: prior